name: Publish .NET Package to NuGet

on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '9.0.x'
  GITHUB_USERNAME: 'SolarBAM404'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Nuget publish MongoDb-EntityFramework
      # You may pin to the exact commit or the version.
      # uses: DmitryLegostaev/DmitryLegostaev.GitHubActions.PushNupkgToGitHub@ac5c50461df2e6736043d33df2e7775e14450ed9
      uses: DmitryLegostaev/DmitryLegostaev.GitHubActions.PushNupkgToGitHub@v1.0.1
      with:
        # Project name
        PROJECT_NAME: MongoDbEntityFramework
        # Key to use with nuget push
        NUGET_API_KEY: "${{ secrets.PAT_GITHUB }}"
        # Github GRP project namespace
        GITHUB_GPR_NAMESPACE: ${{ env.GITHUB_USERNAME }}
        # .NET version to use
        DOTNET_VERSION: ${{ env.DOTNET_VERSION }}
    - name: Nuget publish MongoDb-EntityFramework.Host
      # You may pin to the exact commit or the version.
      # uses: DmitryLegostaev/DmitryLegostaev.GitHubActions.PushNupkgToGitHub@ac5c50461df2e6736043d33df2e7775e14450ed9
      uses: DmitryLegostaev/DmitryLegostaev.GitHubActions.PushNupkgToGitHub@v1.0.1
      with:
        # Project name
        PROJECT_NAME: MongoDbEntityFramework.Host
        # Key to use with nuget push
        NUGET_API_KEY: "${{ secrets.PAT_GITHUB }}"
        # Github GRP project namespace
        GITHUB_GPR_NAMESPACE: ${{ env.GITHUB_USERNAME }}
        # .NET version to use
        DOTNET_VERSION: ${{ env.DOTNET_VERSION }}
