name: Publish .NET Package to NuGet

on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '9.0.x'
  GITHUB_USERNAME: 'SolarBAM404'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Pack with dotnet
      run: dotnet pack --configuration Release

    - name: Add NuGet Source
      run: dotnet nuget add source --username ${{ env.GITHUB_USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ env.GITHUB_USERNAME }}/index.json"

    # - name: Publish to GitHub Packages
    #   run: dotnet nuget push "MongoDbEntityFramework/bin/Release/MongoDbEntityFramework.*.nupkg" --source "github" --skip-duplicate
    
    - name: Nuget publish to GitHub@DmitryLegostaev
      # You may pin to the exact commit or the version.
      # uses: DmitryLegostaev/DmitryLegostaev.GitHubActions.PushNupkgToGitHub@ac5c50461df2e6736043d33df2e7775e14450ed9
      uses: DmitryLegostaev/DmitryLegostaev.GitHubActions.PushNupkgToGitHub@v1.0.1
      with:
        # Project name
        PROJECT_NAME: MongoDbEntityFramework
        # Key to use with nuget push
        NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        # Github GRP project namespace
        GITHUB_GPR_NAMESPACE: ${{ env.GITHUB_USERNAME }}
        # .NET version to use
        DOTNET_VERSION: ${{ env.DOTNET_VERSION }}
          
