name: Publish .NET Package to NuGet

on:
  push:
    branches:
      - master
      - actions/publish

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Pack with dotnet
      run: dotnet pack --configuration Release

    - name: Publish to GitHub Packages
      run: dotnet nuget push "bin/Release/*.nupkg" --api-key ${{ secrets.GITHUB_PAT }} --source "github"
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
